# Generated by Django 5.1.5 on 2025-05-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpt_handler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyprompt",
            name="conversation_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
